EngineerApplication/Areas/Admin/Controllers/OfferController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EngineerApplication.ContextStructure.Data.Service.Interfaces;
using EngineerApplication.Entities.ViewModels;

namespace EngineerApplication.Areas.Admin.Controllers
{
  [Area("Admin")]
  [Authorize]
  public class OfferController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;

    [BindProperty]
    public OfferVM OfferVM { get; set; }

    public OfferController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Upsert(int? id)
    {
      OfferVM = new OfferVM()
      {
        Offer = new Entities.Offer(),
        CommodityList = _unitOfWork.Commodity.GetCommodityListForDropDown(),
      };
      if (id != null)
      {
        OfferVM.Offer = _unitOfWork.Offer.Get(id.GetValueOrDefault());
      }

      return View(OfferVM);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert()
    {
      if (ModelState.IsValid)
      {
        if (OfferVM.Offer.Id == 0)
        {
          _unitOfWork.Offer.Add(OfferVM.Offer);
        }
        else
        {
          var OfferFromDb = _unitOfWork.Offer.Get(OfferVM.Offer.Id);
          _unitOfWork.Offer.Update(OfferVM.Offer);
        }
        _unitOfWork.Save();
        return RedirectToAction(nameof(Index));
      }
      else
      {
        OfferVM.CommodityList = _unitOfWork.Commodity.GetCommodityListForDropDown();
        return View(OfferVM);
      }
    }
    #region API Calls
    public IActionResult GetAll()
    {
      return Json(new { data = _unitOfWork.Offer.GetAll(includeProperties: "Commodity") });
    }

    [HttpDelete]
    public IActionResult Delete(int id)
    {
      var OfferFromDb = _unitOfWork.Offer.Get(id);

      if (OfferFromDb is null)
      {
        return Json(new { success = false, message = "Error while deleting." });
      }

      _unitOfWork.Offer.Remove(OfferFromDb);
      _unitOfWork.Save();
      return Json(new { success = true, message = "Deleted Successfully." });
    }
    #endregion
  }
}

EngineerApplication/Areas/Customer/Controllers/OfferServiceController.cs
#nullable disable
using System.Diagnostics;
using EngineerApplication.ContextStructure.Data.Service.Interfaces;
using EngineerApplication.Entities;
using EngineerApplication.Entities.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EngineerApplication.Areas.Customer.Controllers
{
  [Area("Customer")]
  public class OfferServiceController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;
    private OfferServiceViewModel OfferServiceVM;
    private OfferServiceViewModel OfferServiceVMWithFilter;

    [BindProperty]
    public CommodityVM CommodityVM { get; set; }

    public OfferServiceController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }

    public async Task<IActionResult> OfferService()
    {
      OfferServiceVM = new OfferServiceViewModel()
      {
        CategoryList = await _unitOfWork.Category.GetAllAsync(),
        ServiceList = await _unitOfWork.Service.GetAllAsync(includeProperties: "Category,Payment"),
        EmployeeList = await _unitOfWork.Employee.GetAllAsync(includeProperties: "Service"),
      };

      return View("OfferService", OfferServiceVM);
    }

    [HttpGet("SearchStringService")]
    public async Task<IActionResult> OfferServiceWithFilter(string SearchStringService)
    {
      OfferServiceVMWithFilter = new OfferServiceViewModel()
      {
        CategoryList = await _unitOfWork.Category.GetAllAsync(),
        ServiceList = await _unitOfWork.Service.GetAllAsync(includeProperties: "Category,Payment"),
        EmployeeList = await _unitOfWork.Employee.GetAllAsync(includeProperties: "Service"),
      };

      var resultServices = new List<Service>();

      if (SearchStringService == null)
      {
        resultServices = OfferServiceVMWithFilter.ServiceList.ToList();
      }
      else
      {
        resultServices = OfferServiceVMWithFilter.ServiceList.Where(x => x.Name.ToLower().Contains(SearchStringService)).ToList();
      }

      var result = new OfferServiceViewModel()
      {
        CategoryList = await _unitOfWork.Category.GetAllAsync(),
        ServiceList = resultServices,
        EmployeeList = await _unitOfWork.Employee.GetAllAsync(includeProperties: "Service"),
      };

      return View("OfferServiceWithFilter", result);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

EngineerApplication/Areas/Customer/Views/OfferService/OfferService.cshtml
@using EngineerApplication.Resources
@inject CommonLocalizationService localizer
@model EngineerApplication.Entities.ViewModels.OfferServiceViewModel

<h1 class="text-success">@localizer.Get("OfferService")</h1>
<form asp-controller="OfferService" asp-action="OfferServiceWithFilter" method="get">
    <p>
        <input type="text" id="SearchStringService" name="SearchStringService" />
        <input id="searchButton_" type="submit" value="@localizer.Get("Search")" />
        <ul style="position: relative; display: block; margin: 0 auto; text-align: center; text-decoration: none; width: 90%; padding: 0;">
            <li class="nav-item" style="font-size: 22px; align-items: center; text-decoration: none; height: 48px; width: 186px; color: white; background-color: #32CD32; margin: 0 auto;">
                <a style="float: center; color: white; font-weigt: bold; text-decoration: none;" id="backToOffer_" asp-action="Index" asp-controller="Offer" asp-area="Customer">@localizer.Get("BackToOffer")</a>
            </li>
        </ul>
    </p>
</form>

    @foreach (var category in Model.CategoryList.OrderBy(o => o.Name))
    {
        @if (Model.ServiceList.Where(c => c.CategoryId == category.Id).Count() > 0)
        {
            <div class="row container pb-3 backgroundWhite">
                <h1 class="text-success">@localizer.Get("Services")</h1>
                <div class="col-12">
                    <div class="row">
                        <h2 class="text-success"><b>@category.Name</b></h2>
                        <div class="col-12">
                            <div class="row my-3">
                                @foreach (var Service in Model.ServiceList.Where(c => c.CategoryId == category.Id))
                                {
                                    <div class="col-lg-4 col-xl-3 col-md-6 pb-4">
                                        <div class="card" style="border:2px solid #43ac6a;border-radius:5px; backgroundcolor: #fffeee">
                                            <div class="pl-3 pt-1 text-center">
                                                <h5 id="chosenName" class="card-title text-primary"><b>@Service.Name</b></h5>
                                            </div>
                                            <div class="d-flex justify-content-between ">
                                                <div class="pl-1 text-muted">@localizer.Get("Price") @localizer.Get("PerCommodity")</div>
                                                <div class="pr-1 text-danger h5">@Math.Round(Service.Price, 2).ToString("c", new CultureInfo("pl-PL"))</div>
                                            </div>
                                            <img src="@Service.ImageUrl" class="card-img-top p-2 rounded" width="297" height="245"/>

                                            <div class="text-muted text-center pb-2">@Service.Payment.Name</div>
                                            <div class="pl-3 pt-1 text-center">
                                                @foreach (var Employee in Model.EmployeeList.Where(c => c.ServiceId == Service.Id))
                                                {
                                                    <div class="pl-3 pt-1 text-center">
                                                        <h2 class="card-title text-primary"><b>@Employee.Name</b></h2>
                                                    </div>
                                                    <div class="pl-3 pt-1 text-center">
                                                        <h2 class="card-title text-primary"><b>@Employee.PhoneNumber</b></h2>
                                                    </div>
                                                    <div class="pt-1 text-center">
                                                        <h7 class="card-title text-primary"><b>@Employee.EmailAddress</b></h7>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
}

EngineerApplication/Areas/Customer/Views/OfferService/OfferServiceWithFilter.cshtml
@using EngineerApplication.Resources
@inject CommonLocalizationService localizer
@model EngineerApplication.Entities.ViewModels.OfferServiceViewModel

<h1 class="text-success">@localizer.Get("OfferService")</h1>
    <a class="nav-link" asp-area="Customer" style="font-size: 16px; align-items: center; text-decoration: none; height: 48px; width: 186px; color: white; background-color: #32CD32; margin: 0 auto; float: center; color: white; font-weigt: bold; text-decoration: none;" asp-controller="OfferService" asp-action="OfferService">@localizer.Get("OfferService")</a>
    @foreach (var category in Model.CategoryList.OrderBy(o => o.Name))
    {
        @if (Model.ServiceList.Where(c => c.CategoryId == category.Id).Count() > 0)
        {
            <div class="row container pb-3 backgroundWhite">
                <h1 class="text-success">@localizer.Get("Services")</h1>
                <div class="col-12">
                    <div class="row">
                        <h2 class="text-success"><b>@category.Name</b></h2>
                        <div class="col-12">
                            <div class="row my-3">
                                @foreach (var Service in Model.ServiceList.Where(c => c.CategoryId == category.Id))
                                {
                                    <div class="col-lg-4 col-xl-3 col-md-6 pb-4">
                                        <div class="card" style="border:2px solid #43ac6a;border-radius:5px; backgroundcolor: #fffeee">
                                            <div class="pl-3 pt-1 text-center">
                                                <h5 id="chosenName" class="card-title text-primary"><b>@Service.Name</b></h5>
                                            </div>
                                            <div class="d-flex justify-content-between ">
                                                <div class="pl-1 text-muted">@localizer.Get("Price") @localizer.Get("PerCommodity")</div>
                                                <div class="pr-1 text-danger h5">@(Math.Round(Service.Price, 2).ToString("c", new CultureInfo("pl-PL")))</div>
                                            </div>
                                            <img src="@Service.ImageUrl" class="card-img-top p-2 rounded" width="297" height="245"/>

                                            <div class="text-muted text-center pb-2">@Service.Payment.Name</div>
                                            <div class="pl-3 pt-1 text-center">
                                                @foreach (var Employee in Model.EmployeeList.Where(c => c.ServiceId == Service.Id))
                                                {
                                                    <div class="pl-3 pt-1 text-center">
                                                        <h2 class="card-title text-primary"><b>@Employee.Name</b></h2>
                                                    </div>
                                                    <div class="pl-3 pt-1 text-center">
                                                        <h2 class="card-title text-primary"><b>@Employee.PhoneNumber</b></h2>
                                                    </div>
                                                    <div class="pt-1 text-center">
                                                        <h7 class="card-title text-primary"><b>@Employee.EmailAddress</b></h7>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
}