EngineerApplication/Areas/Admin/Controllers/CommodityController.cs
#nullable disable
using EngineerApplication.ContextStructure.Data.Service.Interfaces;
using EngineerApplication.Entities;
using EngineerApplication.Entities.ViewModels;
using iText.Html2pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EngineerApplication.Areas.Admin.Controllers
{
  [Area("Admin")]
  [Authorize]
  public class CommodityController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;

    [BindProperty]
    public CommodityVM CommodityVM { get; set; }

    public CommodityController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
      _unitOfWork = unitOfWork;
      _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {
      return View("Index");
    }

    public async Task<IActionResult> AddOrUpdate(int? id)
    {
      CommodityVM = new CommodityVM()
      {
        Commodity = new Commodity(),
        CategoryList = _unitOfWork.Category.GetCategoryForCommodityListForDropDown(),
      };
      if (id != null)
      {
        CommodityVM.Commodity = await _unitOfWork.Commodity
          .GetAsync(id.GetValueOrDefault());
      }

      return View(CommodityVM);
    }

    [HttpPost("exportCommodity")]
    public IActionResult Export(string GridHtml)
    {
      using MemoryStream stream = new MemoryStream();
      HtmlConverter.ConvertToPdf(GridHtml, stream);
      return File(stream.ToArray(), "application/pdf", $"CommodityData_{DateTime.Now}.pdf", true);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddOrUpdate()
    {
      if (ModelState.IsValid)
      {
        string webRootPath = _hostEnvironment.WebRootPath;
        var files = HttpContext.Request.Form.Files;
        if (CommodityVM.Commodity.Id == 0)
        {
          string fileName = Guid.NewGuid().ToString();
          var uploads = Path.Combine(webRootPath, @"images\Services");
          var extension = Path.GetExtension(files[0].FileName);

          using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
          {
            files[0].CopyTo(fileStreams);
          }
          CommodityVM.Commodity.ImageUrl = @"\images\Services\" + fileName + extension;

          await _unitOfWork.Commodity.AddAsync(CommodityVM.Commodity);
        }
        else
        {
          var commodityFromDb = await _unitOfWork.Commodity.GetAsync(CommodityVM.Commodity.Id);
          if (files.Count > 0)
          {
            string fileName = Guid.NewGuid().ToString();
            var uploads = Path.Combine(webRootPath, @"images\Services");
            var extension_new = Path.GetExtension(files[0].FileName);

            var imagePath = Path.Combine(webRootPath, commodityFromDb.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(imagePath))
            {
              System.IO.File.Delete(imagePath);
            }

            using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension_new), FileMode.Create))
            {
              files[0].CopyTo(fileStreams);
            }
            CommodityVM.Commodity.ImageUrl = @"\images\Services\" + fileName + extension_new;
          }
          else
          {
            CommodityVM.Commodity.ImageUrl = commodityFromDb.ImageUrl;
          }

          await _unitOfWork.Commodity.UpdateAsync(CommodityVM.Commodity);
        }
        await _unitOfWork.SaveAsync();
        return RedirectToAction(nameof(Index));
      }
      else
      {
        CommodityVM.CategoryList = _unitOfWork.Category.GetCategoryForCommodityListForDropDown();
        return View(CommodityVM);
      }
    }
    #region API Calls
    public async Task<IActionResult> GetAll()
    {
      return Json(new { data = await _unitOfWork.Commodity.GetAllAsync(includeProperties: "Category") });
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(int id)
    {
      var commodityFromDb = await _unitOfWork.Commodity.GetAsync(id);
      string webRootPath = _hostEnvironment.WebRootPath;
      var imagePath = Path.Combine(webRootPath,
        commodityFromDb.ImageUrl.TrimStart('\\'));
      if (System.IO.File.Exists(imagePath))
      {
        System.IO.File.Delete(imagePath);
      }

      if (commodityFromDb is null)
      {
        return Json(new
        {
          success = false,
          message = "Error while deleting."
        });
      }

      _unitOfWork.Commodity.Remove(commodityFromDb);
      await _unitOfWork.SaveAsync();
      return Json(new { success = true, message = "Usunięto prawdiłowo." });
    }
    #endregion
  }
}

EngineerApplication/Areas/Admin/Views/Commodity/AddOrUpdate.cshtml
@inject CommonLocalizationService localizer
@model EngineerApplication.Entities.ViewModels.CommodityVM

@{
    var title = @localizer.Get("CreateCommodity");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form id="commodityForm_" method="post" asp-action="AddOrUpdate" enctype="multipart/form-data">

    <div class="row px-2 mx-2 backgroundWhite border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model.Commodity.Id != 0)
        {
            <input type="hidden" asp-for="Commodity.Id" />
            title = @localizer.Get("EditCommodity");
        }

        <div class="col-12">
            <h2 class="text-primary">@title</h2>
            <br />
        </div>
        <div class="col-10">
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("CommodityName")</label>
                </div>
                <div class="col-8">
                    <input id="commodityName_" asp-for="Commodity.Name" class="form-control" />
                    <span asp-validation-for="Commodity.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Price")</label>
                </div>
                <div class="col-8">
                    <input id="commodityPrice_" asp-for="Commodity.Price" id="txtPrice" class="form-control" />
                    <span asp-validation-for="Commodity.Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Description")</label>
                </div>
                <div class="col-8">
                    <textarea id="commodityDesc_" asp-for="Commodity.LongDesc" class="form-control" style="height:300px;"></textarea>
                    <span asp-validation-for="Commodity.LongDesc" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Photo")</label>
                </div>
                <div class="col-8">
                    <input id="commodityImg_" type="file" name="files" id="uploadBox" multiple class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Category")</label>
                </div>
                <div class="col-8">
                    @Html.DropDownListFor(m => m.Commodity.CategoryId, Model.CategoryList,
                                            @localizer.Get("PleaseSelectACategory"), new { @class = "form-control", @id = "Select-List" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    @if (Model.Commodity.Id != 0)
                    {
                        <partial name="_EditAndBackToListButton" model="Model.Commodity.Id" />
                    }
                    else
                    {
                        <div class="row">
                            <div class="col">
                                <button type="submit" onclick="return validateInput()" class="btn btn-primary form-control">@localizer.Get("Create")</button>
                            </div>
                            <div class="col">
                                <a asp-action="Index" class="btn btn-success form-control">@localizer.Get("BackToList")</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        @if (Model.Commodity.Id != 0)
        {
            <div class="col-3">
                <img src="@Model.Commodity.ImageUrl" width="100" style="border-radius:5px; border:1px solid #bbb9b9" />
            </div>
        }
    </div>

</form>

@section Scripts{
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js"></script>
    <script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'lists',
        menubar: 'file edit format'
    });

    function validateInput() {
        if (document.getElementById("uploadBox").value == "") {
            swal(@localizer.Get("Error"), @localizer.Get("PleaseSelectAnImage"), "error")
            return false;
        }
        return true;
            };

    $(document).ready(function () {
        if (document.getElementById('txtPrice').value == "0") {
            document.getElementById('txtPrice').value = '';
        }
    });
    </script>
}

EngineerApplication/Areas/Admin/Views/Commodity/Index.cshtml
@inject CommonLocalizationService localizer
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="border backgroundWhite">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">@localizer.Get("CommodityList")</h2>
        </div>
        <div class="col-6 text-right">
            <a id="createCommodity_" asp-action="AddOrUpdate" class="btn btn-primary"><i class="fas fa-plus"></i> &nbsp; @localizer.Get("CreateNewCommodity")</a>
        </div>
    </div>
    <br />
    <br />
    <table id="tblData" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>@localizer.Get("Name")</th>
                <th>@localizer.Get("CategoryName")</th>
                <th>@localizer.Get("Price")</th>
                <th>@localizer.Get("Description")</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>
<div class="row">
    <div class="col-12 col-lg-5 offset-lg-1">
        <form asp-action="Export" asp-controller="Commodity" method="post">
            <input type="hidden" name="GridHtml" />
            <input class="btn btn-success" type="submit" id="btnSubmit" value="@localizer.Get("ExportToPdf")" />
        </form>
    </div>
</div>
@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="~/js/commodity.js"></script>
}

EngineerApplication/Areas/Admin/Views/Commodity/Upsert.cshtml
@inject CommonLocalizationService localizer
@model EngineerApplication.Entities.ViewModels.CommodityVM

@{
    var title = @localizer.Get("CreateCommodity");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form id="commodityForm_" method="post" asp-action="Upsert" enctype="multipart/form-data">

    <div class="row px-2 mx-2 backgroundWhite border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model.Commodity.Id != 0)
        {
            <input type="hidden" asp-for="Commodity.Id" />
            title = @localizer.Get("EditCommodity");
        }

        <div class="col-12">
            <h2 class="text-primary">@title</h2>
            <br />
        </div>
        <div class="col-10">
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("CommodityName")</label>
                </div>
                <div class="col-8">
                    <input id="commodityName_" asp-for="Commodity.Name" class="form-control" />
                    <span asp-validation-for="Commodity.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Price")</label>
                </div>
                <div class="col-8">
                    <input id="commodityPrice_" asp-for="Commodity.Price" id="txtPrice" class="form-control" />
                    <span asp-validation-for="Commodity.Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Description")</label>
                </div>
                <div class="col-8">
                    <textarea id="commodityDesc_" asp-for="Commodity.LongDesc" class="form-control" style="height:300px;"></textarea>
                    <span asp-validation-for="Commodity.LongDesc" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label>@localizer.Get("Image")</label>
                </div>
                <div class="col-8">
                    <input id="commodityImg_" type="file" name="files" id="uploadBox" multiple class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Commodity.CategoryId"></label>
                </div>
                <div class="col-8">
                    @Html.DropDownListFor(m => m.Commodity.CategoryId, Model.CategoryList,
                                            @localizer.Get("PleaseSelectACategory"), new { @class = "form-control", @id = "Select-List" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    @if (Model.Commodity.Id != 0)
                    {
                        <partial name="_EditAndBackToListButton" model="Model.Commodity.Id" />
                    }
                    else
                    {
                        <div class="row">
                            <div class="col">
                                <button type="submit" onclick="return validateInput()" class="btn btn-primary form-control">@localizer.Get("Create")</button>
                            </div>
                            <div class="col">
                                <a asp-action="Index" class="btn btn-success form-control">@localizer.Get("BackToList")</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        @if (Model.Commodity.Id != 0)
        {
            <div class="col-3">
                <img src="@Model.Commodity.ImageUrl" width="100" style="border-radius:5px; border:1px solid #bbb9b9" />
            </div>
        }
    </div>

</form>

@section Scripts{
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js"></script>
    <script>

    tinymce.init({
        selector: 'textarea',
        plugins: 'lists',
        menubar: 'file edit format'
    });

    function validateInput() {
        if (document.getElementById("uploadBox").value == "") {
            swal(@localizer.Get("Error"), @localizer.Get("PleaseSelectAnImage"), "error")
            return false;
        }
        return true;
            };

    $(document).ready(function () {
        if (document.getElementById('txtPrice').value == "0") {
            document.getElementById('txtPrice').value = '';
        }
    });
    </script>
}