EngineerApplication/Areas/Customer/Controllers/OrderCustomerController.cs
using EngineerApplication.ContextStructure.Data.Service.Interfaces;
using EngineerApplication.Entities.ViewModels;
using EngineerApplication.Helpers;
using iText.Html2pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EngineerApplication.Areas.Customer.Controllers
{
  [Area("Customer")]
  [Authorize(Roles = UsefulConsts.Customer)]
  public class OrderCustomerController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;
    private readonly UserManager<IdentityUser> _manager;

    public OrderCustomerController(IUnitOfWork unitOfWork, UserManager<IdentityUser> manager)
    {
      _unitOfWork = unitOfWork;
      _manager = manager;
    }

    public async Task<IActionResult> Index()
    {
      var user = await GetCurrentUser();
      string userEmail = user.Email;
      var orderHeaders = await _unitOfWork.OrderHeader.GetAllAsync(x => x.Email.Equals(userEmail));
      return View("Index", orderHeaders);
    }

    [Authorize]
    public async Task<IActionResult> Details(int id)
    {
      OrderViewModel orderVM = new()
      {
        OrderHeader = await _unitOfWork.OrderHeader.GetAsync(id),
        OrderDetails = await _unitOfWork.OrderDetails.GetAllAsync(filter: o => o.OrderHeaderId == id),
      };
      orderVM.TimeToOrder = (await _unitOfWork.OrderHeader.GetAsync(id)).TimeToOrder;
      orderVM.TimeToRealisation = (await _unitOfWork.OrderHeader.GetAsync(id)).TimeToRealisation;
      orderVM.Supplier = await _unitOfWork.Supplier.GetFirstOrDefaultAsync(filter: o => o.Id == orderVM.OrderHeader.SupplierId);
      orderVM.Delivery = await _unitOfWork.Delivery.GetFirstOrDefaultAsync(filter: o => o.Id == orderVM.OrderHeader.DeliveryId);
      orderVM.Payment = await _unitOfWork.Payment.GetFirstOrDefaultAsync(filter: o => o.Id == orderVM.OrderHeader.PaymentId);
      await _unitOfWork.SaveAsync();
      return View(orderVM);
    }

    public async Task<IActionResult> GetAllOrders()
    {
      return Json(new { data = await _unitOfWork.OrderHeader.GetAllAsync() });
    }

    public async Task<IActionResult> GetAllPendingOrders()
    {
      return Json(new { data = await _unitOfWork.OrderHeader.GetAllAsync(filter: o => o.Status == UsefulConsts.StatusSubmitted) });
    }

    public async Task<IActionResult> GetAllApprovedOrders()
    {
      return Json(new { data = await _unitOfWork.OrderHeader.GetAllAsync(filter: o => o.Status == UsefulConsts.StatusApproved) });
    }

    private async Task<IdentityUser> GetCurrentUser()
    {
      return await _manager.GetUserAsync(HttpContext.User);
    }
  }
}

EngineerApplication/Areas/Customer/Views/OrderCustomer/Details.cshtml
@inject CommonLocalizationService localizer
@model EngineerApplication.Entities.ViewModels.OrderViewModel
@using EngineerApplication.Helpers

@{
    ViewData["Title"] = @localizer.Get("Details");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    @if (Model.OrderDetails.Count() > 0)
    {
        <br />
        <div class="backgroundWhite container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-12 d-none d-md-block col-md-6 pb-1">
                        <i class="fas fa-shopping-cart"></i> &nbsp; @localizer.Get("OrderSummary")
                    </div>
                    <div class="col-12 col-md-4 offset-md-2 text-right">
                        <a id="backToOrders_" asp-action="Index" asp-controller="OrderCustomer" asp-area="Customer" class="btn btn-outline-info form-control btn-sm">@localizer.Get("BackToOrders")</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-primary">@localizer.Get("PickUpDetails"):</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Name")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.Name" id="txtName" readonly type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Phone")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.Phone" id="txtPhone" readonly type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Address")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.Address" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("City")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.City" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("ZipCode")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.ZipCode" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Email")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.Email" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("TimeToOrder")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.TimeToOrder" type="date" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("TimeToRealisation")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.TimeToRealisation" type="date" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Supplier")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Supplier.Name" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Delivery")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Delivery.Name" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>@localizer.Get("Payment")</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Payment.Name" type="text" readonly class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-primary">@localizer.Get("OrderSummary")</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    @{
                                        var total = 0.0;
                                    }

                                    @foreach (var details in Model.OrderDetails)
                                    {
                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <input type="hidden" asp-for="@details.Id" />
                                                <h5 class="my-0">@details.CommodityName</h5><br/>
                                                <h7 class="text-muted">@localizer.Get("AmountInOrder") : @details.AmountInOrder</h7><br/>
                                                <h7 class="text-muted">@localizer.Get("PriceUnit") :  @(Math.Round(details.Price, 2).ToString("C", new CultureInfo("pl-PL")))</h7><br/>
                                                <h7 class="text-muted">@localizer.Get("Price") : @(Math.Round((details.Price * @details.AmountInOrder), 2).ToString("C", new CultureInfo("pl-PL")))</h7><br/>
                                                <h7 class="text-muted">@localizer.Get("VATPrice") : @(Math.Round((0.23 * (details.Price * @details.AmountInOrder)), 2).ToString("C", new CultureInfo("pl-PL")))</h7><br/>
                                                <h7 class="text-muted">@localizer.Get("NettoPrice") : @(Math.Round((0.77 * (details.Price * @details.AmountInOrder)), 2).ToString("C", new CultureInfo("pl-PL")))</h7>
                                            </div>
                                        </li>
                                    }
                                    <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h7 class="text-muted">@localizer.Get("OrderSummary") :  @(Math.Round(Model.OrderDetails.Sum(x => (x.Price * x.AmountInOrder)), 2).ToString("C", new CultureInfo("pl-PL")))</h7><br/>
                                                <h7 class="text-muted">@localizer.Get("TimeToRealisation") :  @(Model.TimeToRealisation)</h7>
                                            </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="backgroundWhite">@localizer.Get("NoItemsAdded")</div>
    }
</form>

EngineerApplication/Areas/Customer/Views/OrderCustomer/Index.cshtml
@using EngineerApplication.Extensions
@using EngineerApplication.Helpers
@using Microsoft.AspNetCore.Http
@using EngineerApplication.Entities
@using EngineerApplication.Resources
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@using EngineerApplication.Helpers
@inject CommonLocalizationService localizer
@model IEnumerable<OrderHeader>

@{
    ViewData["Title"] = @localizer.Get("Index");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="border backgroundWhite">
    <div class="d-flex justify-content-between mb-3">
        <div class="p-2">
            <h2 class="text-primary">@localizer.Get("OrdersList")</h2>
        </div>
    </div>
    @if (Model.Count() > 0)
    {
        <table id="tblData" class="table table-striped border">
            <tr class="table-secondary">
                <th>
                    @localizer.Get("Name")
                </th>
                <th>
                    @localizer.Get("Phone")
                </th>
                <th>
                    @localizer.Get("Email")
                </th>
                <th>
                    @localizer.Get("Status")
                </th>
                <th>
                    @localizer.Get("TimeToOrder")
                </th>
                <th>
                    @localizer.Get("TimeToRealisation")
                </th>
                <th></th>
            </tr>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Status)
                    </td>
                    <th>
                        @Html.DisplayFor(m => item.TimeToOrder)
                    </th>
                    <th>
                        @Html.DisplayFor(m => item.TimeToRealisation)
                    </th>
                    <td>
                        <div class="text-center">
                            <a id="orderDetails_" href="/Customer/OrderCustomer/Details/@(item.Id)" class='btn btn-success text-white' style='cursor:pointer; width:100px;'>
                                <i class='far fa-edit'></i> @localizer.Get("Details")
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>@localizer.Get("NoOrderExists")...</p>
    }
</div>